/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Kinetic Precision Design System — Surface Architecture
        'surface': '#f5f7f9',
        'surface-bright': '#f5f7f9',
        'surface-dim': '#d0d5d8',
        'surface-variant': '#d9dde0',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eef1f3',
        'surface-container': '#e5e9eb',
        'surface-container-high': '#dfe3e6',
        'surface-container-highest': '#d9dde0',
        'surface-tint': '#9c3f00',
        'inverse-surface': '#0b0f10',
        'inverse-on-surface': '#9a9d9f',
        'background': '#f5f7f9',
        'on-background': '#2c2f31',
        // Primary — Orange energy
        'primary': '#9c3f00',
        'primary-dim': '#893600',
        'primary-container': '#ff7a2f',
        'primary-fixed': '#ff7a2f',
        'primary-fixed-dim': '#f66700',
        'on-primary': '#fff0ea',
        'on-primary-container': '#401500',
        'on-primary-fixed': '#000000',
        'on-primary-fixed-variant': '#4f1c00',
        'inverse-primary': '#fe6b00',
        // Secondary — Cool slate
        'secondary': '#535b71',
        'secondary-dim': '#484f65',
        'secondary-container': '#dae2fd',
        'secondary-fixed': '#dae2fd',
        'secondary-fixed-dim': '#ccd4ee',
        'on-secondary': '#f0f2ff',
        'on-secondary-container': '#4a5167',
        'on-secondary-fixed': '#373f54',
        'on-secondary-fixed-variant': '#535b71',
        // Tertiary — Amber/gold
        'tertiary': '#7a5400',
        'tertiary-dim': '#6b4900',
        'tertiary-container': '#fbb423',
        'tertiary-fixed': '#fbb423',
        'tertiary-fixed-dim': '#eba60f',
        'on-tertiary': '#fff1df',
        'on-tertiary-container': '#523700',
        'on-tertiary-fixed': '#372400',
        'on-tertiary-fixed-variant': '#5e4000',
        // Error
        'error': '#b02500',
        'error-dim': '#b92902',
        'error-container': '#f95630',
        'on-error': '#ffefec',
        'on-error-container': '#520c00',
        // On-surfaces
        'on-surface': '#2c2f31',
        'on-surface-variant': '#595c5e',
        // Outlines
        'outline': '#747779',
        'outline-variant': '#abadaf',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        sm: '0.125rem',
        md: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      boxShadow: {
        'cloud-sm': '0 4px 20px -10px rgba(44,47,49,0.06)',
        'cloud-md': '0 8px 30px -15px rgba(44,47,49,0.08)',
        'cloud-lg': '0 40px 60px rgba(44,47,49,0.06)',
        'primary-glow': '0 8px 20px -6px rgba(156,63,0,0.4)',
        'primary-glow-sm': '0 4px 14px rgba(156,63,0,0.3)',
        'nav': '0 -8px 40px -12px rgba(0,0,0,0.1)',
      },
    },
  },
  plugins: [],
}

